name: Grammar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  textidote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install textidote
        run: |
          wget https://github.com/sylvainhalle/textidote/releases/download/v0.8.1/textidote_0.8.1_all.deb
          sudo dpkg -i textidote_0.8.1_all.deb
      # Storage dir
      - name: temp dir
        run: mkdir temp
      # The actual check
      - name: Check document
        run: for file in `ls content`; do textidote --check en --type md content/$file || true; done
      # Make HTML interface
      - name: Create HTML document
        run: for file in `ls content`; do textidote --check en --type md --output html content/$file > temp/$file.html|| true; done
      - uses: actions/upload-artifact@v2
        with:
          name: HTMLout
          path: temp
  aspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install aspell
        run: sudo apt install aspell-en aspell
      - name: Check with aspell
        run: for file in `ls content`; do echo "  " $file; cat content/$file | aspell --lang=en list; done
      - name: aspell_dir
        run: pwd ; ls ; ls ~
  mdspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install mdspell
        run: npm install
      - name: Check with mdspell
        run: ./node_modules/markdown-spellcheck/bin/mdspell content/*.md
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check markdown
        run: docker run -v $(pwd):/app --workdir=/app coala/base coala --ci --files content/*.md --bears=MarkdownBear
        
