name: Grammar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install textidote
        run: |
          wget https://github.com/sylvainhalle/textidote/releases/download/v0.8.1/textidote_0.8.1_all.deb
          sudo dpkg -i textidote_0.8.1_all.deb
      # The actual check
      - name: Check document
        run: textidote --check en main.tex || true
      # Make HTML interface
      - name: Create HTML document
        run: textidote --output html --check en main.tex > html.html || true
      - uses: actions/upload-artifact@v2
        with:
          name: HTMLout
          path: html.html

